const GET_USER = 'GET_USER'
const GET_USER_RECIPES = 'GET_USER_RECIPES'
const ADD_RECIPE = 'ADD_RECIPE'
const PROFILE_ERROR = 'PROFILE_ERROR'
const RECIPE_ERROR = 'RECIPE_ERROR'
const LOGOUT = 'LOGOUT'
const ADD_FRIEND = 'ADD_FRIEND'
const REMOVE_FRIEND = 'REMOVE_FRIEND'

module.exports = {
    GET_USER,
    GET_USER_RECIPES,
    ADD_RECIPE,
    LOGOUT,
    PROFILE_ERROR,
    RECIPE_ERROR,
    ADD_FRIEND,
    REMOVE_FRIEND
}